### ISSUE TITLE
White Background on NPC Sheets

### ISSUE THREAD

**Issue by DivertedCircle** [RedReign/Roll20-Dark-Theme#1]
Recent Roll20 changes have caused the NPC sheets to have a white background, making it very hard to read.

![image](https://user-images.githubusercontent.com/26470570/51069409-d82f7f00-15eb-11e9-9b40-066fb2251ae8.png)

**Comment by DivertedCircle** [comment]
Getting this in a couple spots on PC sheets as well now with their updates this week to the 5e OGL sheet.

**Comment by RedReign** [comment]
Seems to be fixed by deleting and reinstalling the script.
