### ISSUE TITLE
Shifted display

### ISSUE THREAD

**Issue by Angor-de-Redjak** [RedReign/Roll20-Dark-Theme#5]
Hello!

So I previously used VTTES Dark Theme and I wanted to continue using it so I came here to use yours.
I'm french and it seems that Roll20 french display does weird things when your Dark Theme is enabled. Would it be possible to do something about this?

This is not really hurtful but it keeps disturbing me...

Thank you and nice work here!

![RedReignpb](https://user-images.githubusercontent.com/45643509/54470177-ecd2f380-47a3-11e9-8e8f-14227fe61ed2.png)

**Comment by RedReign** [comment]
Ah. I think you'll be interested to hear that it's not just a problem for French!

The main issue is that it's a new symbol added by Roll20 that they didn't add using pictos, like the other icons are. Instead, it uses an <img> tag (also shows why it's transparent).

I've fixed the alignment though, and it should appear fine now.

**Comment by Angor-de-Redjak** [comment]
Thank you very much!
